<a href="https://colab.research.google.com/github/Mich-088/MAT422/blob/main/Least_Squares_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# 1.3.2 Least-squares problems
# Suppose we have a n x m matrix A ∈ R^(nxm)
# Suppose ve have a vector b where b ∈ R^(n)
# In the lest aquares problem, we use Ax to approximate b.
# In other words, Ax ≈ b

import numpy as np
from IPython.display import display, Markdown

# Creating array A
A = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],
], dtype = float)

# Creating vector b
b = np.array([3, 7, 11, 15, 20], dtype = float)

# Finding the least squares solution
x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond = None)

# Calsulating residual vector
residual = b - A @ x

# ==============================================================================

print("\n")
display(Markdown("LEAST SQUARES PROBLEM:"))
print("________________________________________")
print("\n")
display(Markdown("A ="))
print(A)

print("\n")
print("________________________________________")
print("\n")
display(Markdown("\nb ="))
print(b)

print("\n")
print("________________________________________")
print("\n")
display(Markdown("\nLeast squares solution: "))
print("\nx = ")
print(x)

print("\n")
print("________________________________________")
print("\n")

display(Markdown("\nA @ x ="))
print(A @ x)

print("\n")
print("________________________________________")
print("\n")

# Getting our residual & residual norm
# This tells us how far our least-squares solution is
# from getting the exact solution
display(Markdown("\nResidual vector b - A @ x ="))
print(residual)

print("\n")
display(Markdown("\nResidual norm ="))
print("\n")
print(np.linalg.norm(residual))

print("\n")
print("________________________________________")
print("\n")
display(Markdown("\nSingular Values ="))
print("\n")
print(singular_values)

print("\n")
print("________________________________________")
print("\n")

# Check if residual is perpendicular to columns of A
# A^(T) (b - Ax) = 0
display(Markdown("\nnormal-equation check A.T @ residual ="))
print("\n")
print(A.T @ residual)
print("\n")

print(
    "Residual is orthogonal to columns of A?",
    np.allclose(A.T @ residual, 0)
)










LEAST SQUARES PROBLEM:

________________________________________




A =

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]


________________________________________





b =

[ 3.  7. 11. 15. 20.]


________________________________________





Least squares solution: 


x = 
[1.4 0.7]


________________________________________





A @ x =

[ 2.8  7.  11.2 15.4 19.6]


________________________________________





Residual vector b - A @ x =

[ 2.00000000e-01 -2.66453526e-15 -2.00000000e-01 -4.00000000e-01
  4.00000000e-01]





Residual norm =



0.6324555320336761


________________________________________





Singular Values =



[19.60815689  0.72123738]


________________________________________





normal-equation check A.T @ residual =



[-5.32907052e-14 -6.57252031e-14]


Residual is orthogonal to columns of A? True
