<a href="https://colab.research.google.com/github/Mich-088/MAT422/blob/main/QR_Decompositon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1.3.1 QR Decomposition
# QR decomposition is a convinient and useful way to solve
# the linear least squares problem

import numpy as np
from IPython.display import display, Markdown

A = np.array([
    [1,1],
    [1,0],
    [0,1],
    [1,2]
])

Q, R = np.linalg.qr(A) # perform QR decomposition on matrix A and store the two resulting matricies in Q & R

print("\n")
display(Markdown("A ="))
print(A)

print ("\n_______________________________________")
print("\n")

display(Markdown("\nQ ="))
print(Q)

display(Markdown("\nR ="))
print(R)

print ("\n_______________________________________")
print("\n")

display(Markdown("\nQ @ R ="))
print(Q @ R)

#ROUND Q TO INTEGERS SO IT COULD BE MORE EASILYU SEEN THAT QR = A
QmultR = np.round(Q @ R).astype(int)

print ("\n_______________________________________")
print("\n")

display(Markdown("\nQ @ R rounded to integers = "))
print(QmultR)

# CHECK IF Q HAS ORTHONORMAL COLUMNS:
print ("\n_______________________________________")
print("\n")

display(Markdown("\nDoes Q have orthomnormal columns?"))
print("\n",np.allclose(Q.T @ Q, np.eye(Q.shape[1])))

print("\n")

# CHECK IF QR = A
display(Markdown("\nDoes Q @ R Recunstruct A?"))
print("\n",np.allclose(Q @ R, A))








A =

[[1 1]
 [1 0]
 [0 1]
 [1 2]]

_______________________________________





Q =

[[-0.57735027  0.        ]
 [-0.57735027 -0.57735027]
 [-0.          0.57735027]
 [-0.57735027  0.57735027]]



R =

[[-1.73205081 -1.73205081]
 [ 0.          1.73205081]]

_______________________________________





Q @ R =

[[1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 4.85286907e-18]
 [0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 2.00000000e+00]]

_______________________________________





Q @ R rounded to integers = 

[[1 1]
 [1 0]
 [0 1]
 [1 2]]

_______________________________________





Does Q have orthomnormal columns?


 True





Does Q @ R Recunstruct A?


 True
